@u_lar_be_HostAddress = http://localhost:5116

### OpenAPI document

GET {{u_lar_be_HostAddress}}/openapi/v1.json
Accept: application/json


### Login Admin

POST {{u_lar_be_HostAddress}}/api/v1/Auth/login
Content-Type: application/json
Accept: application/json

{
  "nim": "ADMIN001",
  "password": "Admin123!"
}

### Get Students

GET {{u_lar_be_HostAddress}}/api/v1/Admin/students
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IlUtTEFSIEFkbWluaXN0cmF0b3IiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkB1bGFyLmxvY2FsIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJuaW0iOiJBRE1JTjAwMSIsImV4cCI6MTc4NjM3NDE3NCwiaXNzIjoidS1sYXItYXBpIiwiYXVkIjoidS1sYXItY2xpZW50In0.IFNmXsyYcYoQrXoHx6VC5Yy_gvyz1C0zAKKEtnY8yKA
Accept: application/json


### Create Student

POST {{u_lar_be_HostAddress}}/api/v1/Admin/students
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IlUtTEFSIEFkbWluaXN0cmF0b3IiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkB1bGFyLmxvY2FsIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJuaW0iOiJBRE1JTjAwMSIsImV4cCI6MTc4NjM3NDE3NCwiaXNzIjoidS1sYXItYXBpIiwiYXVkIjoidS1sYXItY2xpZW50In0.IFNmXsyYcYoQrXoHx6VC5Yy_gvyz1C0zAKKEtnY8yKA
Content-Type: application/json
Accept: application/json

{
  "nim": "65748254",
  "name": "Mahasiswa Test 003",
  "email": "mahasiswa003@test.com",
  "password": "Student123!"
}

### Login Student

POST {{u_lar_be_HostAddress}}/api/v1/Auth/login
Content-Type: application/json
Accept: application/json

{
  "nim": "23076052",
  "password": "Student123!"
}

### TEST MAHASISWA TIDAK BISA MEMBUAT AKUN
POST {{u_lar_be_HostAddress}}/api/v1/Admin/students
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Ik1haGFzaXN3YSBUZXN0IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoibWFoYXNpc3dhQHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoic3R1ZGVudCIsIm5pbSI6IjIzMDc2MDUyIiwiZXhwIjoxNzg2MzcyMzIxLCJpc3MiOiJ1LWxhci1hcGkiLCJhdWQiOiJ1LWxhci1jbGllbnQifQ.qZxGrRFxdzQBHNDiHz95RkbeJDPvTx5CU32gW4FCaAo
Content-Type: application/json

{
  "nim": "23076053",
  "name": "Mahasiswa Lain",
  "email": "lain@test.com",
  "password": "Student123!"
}

### Admin protected endpoint

GET {{u_lar_be_HostAddress}}/api/v1/Admin/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IlUtTEFSIEFkbWluaXN0cmF0b3IiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkB1bGFyLmxvY2FsIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJuaW0iOiJBRE1JTjAwMSIsImV4cCI6MTc4NjM3MTk5OSwiaXNzIjoidS1sYXItYXBpIiwiYXVkIjoidS1sYXItY2xpZW50In0.200YMZYS2bZQLvon_Jp2B-qS2FCUJ7V5DQDbeMTh4h0
Accept: application/json