// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using u_lar_be.Infrastructure.Persistence;

#nullable disable

namespace u_lar_be.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917051621_AddMaterials")]
    partial class AddMaterials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("u_lar_be.Domain.Exams.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("PassingScore")
                        .HasColumnType("integer")
                        .HasColumnName("passing_score");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_exams");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_exams_is_active");

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("u_lar_be.Domain.Exams.ExamAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("text")
                        .HasColumnName("answer_text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("boolean")
                        .HasColumnName("is_flagged");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int>("ResultId")
                        .HasColumnType("integer")
                        .HasColumnName("result_id");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<int?>("SelectedOptionId")
                        .HasColumnType("integer")
                        .HasColumnName("selected_option_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_exam_answers");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_exam_answers_question_id");

                    b.HasIndex("SelectedOptionId")
                        .HasDatabaseName("ix_exam_answers_selected_option_id");

                    b.HasIndex("ResultId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_exam_answers_result_id_question_id");

                    b.ToTable("exam_answers", (string)null);
                });

            modelBuilder.Entity("u_lar_be.Domain.Exams.ExamOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("option_text");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_exam_options");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_exam_options_question_id");

                    b.ToTable("exam_options", (string)null);
                });

            modelBuilder.Entity("u_lar_be.Domain.Exams.ExamQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerKey")
                        .HasColumnType("text")
                        .HasColumnName("answer_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExamId")
                        .HasColumnType("integer")
                        .HasColumnName("exam_id");

                    b.Property<string>("Image")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("image");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer")
                        .HasColumnName("order_number");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("question_text");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_exam_questions");

                    b.HasIndex("ExamId", "OrderNumber")
                        .HasDatabaseName("ix_exam_questions_exam_id_order_number");

                    b.ToTable("exam_questions", (string)null);
                });

            modelBuilder.Entity("u_lar_be.Domain.Exams.ExamResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<int>("ExamId")
                        .HasColumnType("integer")
                        .HasColumnName("exam_id");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_exam_results");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("ix_exam_results_exam_id");

                    b.HasIndex("StudentId", "ExamId")
                        .HasDatabaseName("ix_exam_results_student_id_exam_id");

                    b.HasIndex("StudentId", "ExamId", "Attempt")
                        .IsUnique()
                        .HasDatabaseName("ix_exam_results_student_id_exam_id_attempt");

                    b.ToTable("exam_results", (string)null);
                });

            modelBuilder.Entity("u_lar_be.Domain.Materials.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("module_code");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer")
                        .HasColumnName("order_number");

                    b.Property<int>("ReadMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("read_minutes");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("subtitle");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_materials");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_materials_slug");

                    b.HasIndex("IsActive", "OrderNumber")
                        .HasDatabaseName("ix_materials_is_active_order_number");

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("u_lar_be.Domain.Users.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_admins");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_admins_username");

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("u_lar_be.Domain.Users.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Nim")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nim");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_students_email");

                    b.HasIndex("Nim")
                        .IsUnique()
                        .HasDatabaseName("ix_students_nim");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("u_lar_be.Domain.Users.StudentRefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_student_refresh_tokens");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_student_refresh_tokens_student_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_student_refresh_tokens_token_hash");

                    b.ToTable("student_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("u_lar_be.Domain.Exams.ExamAnswer", b =>
                {
                    b.HasOne("u_lar_be.Domain.Exams.ExamQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_answers_exam_questions_question_id");

                    b.HasOne("u_lar_be.Domain.Exams.ExamResult", "Result")
                        .WithMany("Answers")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_answers_exam_results_result_id");

                    b.HasOne("u_lar_be.Domain.Exams.ExamOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_exam_answers_exam_options_selected_option_id");

                    b.Navigation("Question");

                    b.Navigation("Result");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("u_lar_be.Domain.Exams.ExamOption", b =>
                {
                    b.HasOne("u_lar_be.Domain.Exams.ExamQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_options_exam_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("u_lar_be.Domain.Exams.ExamQuestion", b =>
                {
                    b.HasOne("u_lar_be.Domain.Exams.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_questions_exams_exam_id");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("u_lar_be.Domain.Exams.ExamResult", b =>
                {
                    b.HasOne("u_lar_be.Domain.Exams.Exam", "Exam")
                        .WithMany("Results")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_results_exams_exam_id");

                    b.HasOne("u_lar_be.Domain.Users.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_results_students_student_id");

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("u_lar_be.Domain.Materials.Material", b =>
                {
                    b.OwnsMany("u_lar_be.Domain.Materials.MaterialAccordionItem", "Accordion", b1 =>
                        {
                            b1.Property<int>("MaterialId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Body")
                                .IsRequired();

                            b1.Property<string>("Title")
                                .IsRequired();

                            b1.HasKey("MaterialId", "__synthesizedOrdinal");

                            b1.ToTable("materials");

                            b1
                                .ToJson("accordion")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MaterialId")
                                .HasConstraintName("fk_materials_materials_material_id");
                        });

                    b.OwnsMany("u_lar_be.Domain.Materials.MaterialCallout", "Callouts", b1 =>
                        {
                            b1.Property<int>("MaterialId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Body")
                                .IsRequired();

                            b1.Property<string>("Label")
                                .IsRequired();

                            b1.Property<string>("Tone")
                                .IsRequired();

                            b1.HasKey("MaterialId", "__synthesizedOrdinal");

                            b1.ToTable("materials");

                            b1
                                .ToJson("callouts")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MaterialId")
                                .HasConstraintName("fk_materials_materials_material_id");
                        });

                    b.OwnsMany("u_lar_be.Domain.Materials.MaterialDiagram", "Diagrams", b1 =>
                        {
                            b1.Property<int>("MaterialId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Caption")
                                .IsRequired();

                            b1.Property<string>("ImageUrl");

                            b1.HasKey("MaterialId", "__synthesizedOrdinal");

                            b1.ToTable("materials");

                            b1
                                .ToJson("diagrams")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MaterialId")
                                .HasConstraintName("fk_materials_materials_material_id");
                        });

                    b.OwnsMany("u_lar_be.Domain.Materials.MaterialKeyPoint", "KeyPoints", b1 =>
                        {
                            b1.Property<int>("MaterialId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Icon")
                                .IsRequired();

                            b1.Property<string>("Text")
                                .IsRequired();

                            b1.HasKey("MaterialId", "__synthesizedOrdinal");

                            b1.ToTable("materials");

                            b1
                                .ToJson("key_points")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MaterialId")
                                .HasConstraintName("fk_materials_materials_material_id");
                        });

                    b.Navigation("Accordion");

                    b.Navigation("Callouts");

                    b.Navigation("Diagrams");

                    b.Navigation("KeyPoints");
                });

            modelBuilder.Entity("u_lar_be.Domain.Users.StudentRefreshToken", b =>
                {
                    b.HasOne("u_lar_be.Domain.Users.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_refresh_tokens_students_student_id");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("u_lar_be.Domain.Exams.Exam", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("u_lar_be.Domain.Exams.ExamQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("u_lar_be.Domain.Exams.ExamResult", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
